# Generated by Django 5.0.6 on 2024-07-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category__name', 'distance_to_sun']},
        ),
        migrations.AddField(
            model_name='product',
            name='distance_to_sun',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
