# Generated by Django 5.0.6 on 2024-07-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='todays_deal',
            field=models.BooleanField(default=False),
        ),
    ]
