# Generated by Django 5.0.6 on 2024-07-31 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_product_area_product_atmosphere_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='constellation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='geological_activity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='habitable',
        ),
        migrations.RemoveField(
            model_name='product',
            name='magnetic_field',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_stars',
        ),
        migrations.RemoveField(
            model_name='product',
            name='moons',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mythology',
        ),
        migrations.RemoveField(
            model_name='product',
            name='orbital_distance',
        ),
        migrations.RemoveField(
            model_name='product',
            name='orbital_distance_from_planet',
        ),
        migrations.RemoveField(
            model_name='product',
            name='orbital_period',
        ),
        migrations.RemoveField(
            model_name='product',
            name='parent_planet',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rings',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rotation_period',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tidal_effects',
        ),
        migrations.RemoveField(
            model_name='product',
            name='visibility',
        ),
    ]
