# Generated by Django 5.0.6 on 2024-07-31 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_product_composition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='best_viewing_time',
        ),
    ]
