# Generated by Django 5.0.6 on 2024-07-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_product_best_viewing_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='area',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discovery_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quadrant',
        ),
        migrations.AddField(
            model_name='product',
            name='age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
