# Generated by Django 5.0.6 on 2024-07-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_product_area_remove_product_discovery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='distance_to_earth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='distance_to_sun',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
