# Generated by Django 5.0.6 on 2024-08-01 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_product_distance_to_earth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstellationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_to_earth', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('brightest_star', models.CharField(max_length=255)),
                ('best_viewing_time', models.CharField(max_length=255)),
                ('significant_stars_objects', models.TextField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='constellation_detail', to='api.product')),
            ],
        ),
    ]
